/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include <stdint.h>

/* --- АДРЕСА РЕГИСТРОВ (из Reference Manual RM0008) --- */

// 1. Управление тактированием (RCC - Reset and Clock Control)
// Базовый адрес RCC: 0x4002 1000
#define RCC_BASE      0x40021000UL

// Регистр включения тактирования периферии APB2 (смещение 0x18)
#define RCC_APB2ENR   (*(volatile uint32_t *)(RCC_BASE + 0x18))

// 2. Порт ввода-вывода C (GPIOC)
// Базовый адрес GPIOC: 0x4001 1000
#define GPIOC_BASE    0x40011000UL

// Регистр конфигурации (High) для пинов 8-15 (смещение 0x04)
#define GPIOC_CRH     (*(volatile uint32_t *)(GPIOC_BASE + 0x04))

// Регистр данных на выходе (смещение 0x0C)
#define GPIOC_ODR     (*(volatile uint32_t *)(GPIOC_BASE + 0x0C))


/* --- РЕГИСТРЫ SYSTICK (встроены в ядро процессора) --- */
#define SYSTICK_BASE  0xE000E010UL
#define STK_CTRL      (*(volatile uint32_t *)(SYSTICK_BASE + 0x00)) // Управление и статус
#define STK_LOAD      (*(volatile uint32_t *)(SYSTICK_BASE + 0x04)) // Значение для перезагрузки
#define STK_VAL       (*(volatile uint32_t *)(SYSTICK_BASE + 0x08)) // Текущее значение

// Функция задержки в миллисекундах
void delay_ms(uint32_t ms) {
	// 1. Устанавливаем количество тактов для 1 миллисекунды.
    // По умолчанию STM32F103 после сброса работает на частоте 8 МГц (HSI).
    // Значит, 1 мс = 8 000 000 / 1000 = 8000 тактов.
	// Мы просто записали число в память. Таймер стоит.

    STK_LOAD = 8000 - 1;

    // 2. Сбрасываем текущее значение таймера
    // Мы обнулили текущее значение счетчика. Таймер всё еще стоит.

    STK_VAL = 0;

     // 3. Запускаем таймер:
     // Бит 0 (ENABLE): 1 - включить
     // Бит 2 (CLKSOURCE): 1 - использовать частоту процессора
     // ВОТ ЗДЕСЬ ОН ПОЕХАЛ!
     // Мы устанавливаем 0-й бит (ENABLE) в регистре STK_CTRL.

     STK_CTRL = (1 << 0) | (1 << 2);

     for (uint32_t i = 0; i < ms; i++) {
     // Ждем, пока 16-й бит (COUNTFLAG) не станет равен 1.
     // Этот бит автоматически ставится в 1, когда таймер досчитал до 0.
    	 while (!(STK_CTRL & (1 << 16)));
    	 }

     // 4. Выключаем таймер после завершения
     STK_CTRL = 0;
     }




int main(void)
{
	/* ШАГ 1: Включаем тактирование порта C */
	// В регистре RCC_APB2ENR за порт C отвечает 4-й бит (IOPCEN)
	RCC_APB2ENR |= (1 << 4);

	/* ШАГ 2: Настройка PC13 на выход */
	// Настройки каждого пина занимают 4 бита. Для PC13 это биты [23:20] в регистре CRH.
	// Сначала очищаем эти 4 бита (маска 0xF = 1111)
	GPIOC_CRH &= ~(0xF << 20);

	// Устанавливаем режим: Output 2MHz (0x2) и Push-Pull (0x0). Итого 0x2.
	GPIOC_CRH |= (0x2 << 20);

	/* ШАГ 3: Основной цикл */
	while(1)
		{
		// Переключаем (XOR) 13-й бит в регистре данных
		GPIOC_ODR ^= (1 << 13);

		// Простая задержка (программный цикл)
		for(volatile uint32_t i = 0; i < 500000; i++);
		}
}

